setwd("/home/hshziwo/공부/R/방송통신대/회귀모형/기말")
animal = read.csv("./animal.csv", header = FALSE, sep = ",")
head(animal)
animal.lm = lm(V4 ~ V3, data = animal)
plot( animal$V3, animal$V4, pch=19)
plot( animal.lm$fitted.values, animal.lm$residuals, pch= 19)
# install.packages("car")
library(car)
ncvTest(animal.lm)

summary(animal.lm)
outlierTest(animal.lm)
Di = cooks.distance(animal.lm)
round(Di, 3)
# install.packages("mvnormtest")
library(mvnormtest)
animal.rstudent = rstudent(animal.lm)
shapiro.test(animal.rstudent)

animal.loglm = lm(log(V4) ~ log(V3), data = animal)
ncvTest(animal.loglm)
plot( log(animal$V3), log(animal$V4), pch=19)
library(mvnormtest)
animal.logrstudent = rstudent(animal.loglm)
shapiro.test(animal.logrstudent)
