setwd("/home/hshziwo/공부/R/방송통신대/회귀모형/2.다중회귀모형")
factory = read.table("./ex2", header=T, sep="\t")
factory.lm = lm(y ~ x1 + x2, data=factory)
summary(factory.lm) #2.(1),(2)
predict(factory.lm, newdata = data.frame(x1 = 200, x2=59), se.fit = TRUE) #2.(3)
anova(factory.lm)
summary(factory.lm) #2.(4),(5),(6)
library(lm.beta)
factory.beta = lm.beta(factory.lm)
summary(factory.beta)
