# install.packages("distrEx")
library(distrEx)
Poisson_2 = Pois(2)
Binom_21 = Binom(10, 0.2)
Binom_22 = Binom(100, 0.02)
par(mfrow = c(3,1))
plot(Poisson_2, mfColRow = FALSE, to.draw.arg="d", ylab="")
plot(Binom_21, mfColRow = FALSE, to.draw.arg="d", ylab="", xlim=c(0,12))
plot(Binom_22, mfColRow = FALSE, to.draw.arg="d", ylab="", xlim=c(0,12))

# install.packages("mosaic")
library(mosaic)
plotDist("binom", size=100, prob=.5, col=2, lwd=2)
plotDist("norm", mean=50, sd=sqrt(100 * .5 * .5), add=TRUE)
